mariadb-main: follow HA_EXTRA_xxx changes (#1075)
MariaDB use HA_EXTRA_BEGIN_COPY, HA_EXTRA_END_COPY, and
HA_EXTRA_ABORT_COPY instead of HA_EXTRA_BEGIN_ALTER_COPY,
HA_EXTRA_END_ALTER_COPY, and HA_EXTRA_ABORT_ALTER_COPY.

ref:
https://github.com/MariaDB/server/commit/e5fed9eaf49419fe81d3695a4323816db1df8e32

Fix the following errors by this modification.

```
/home/runner/work/mroonga/mroonga/mariadb/storage/mroonga/ha_mroonga.cpp:654:8: error: ‘HA_EXTRA_BEGIN_ALTER_COPY’ was not declared in this scope; did you mean ‘HA_EXTRA_BEGIN_COPY’?
  654 |   case HA_EXTRA_BEGIN_ALTER_COPY:
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |        HA_EXTRA_BEGIN_COPY
/home/runner/work/mroonga/mroonga/mariadb/storage/mroonga/ha_mroonga.cpp:657:8: error: ‘HA_EXTRA_END_ALTER_COPY’ was not declared in this scope; did you mean ‘HA_EXTRA_END_COPY’?
  657 |   case HA_EXTRA_END_ALTER_COPY:
      |        ^~~~~~~~~~~~~~~~~~~~~~~
      |        HA_EXTRA_END_COPY
/home/runner/work/mroonga/mroonga/mariadb/storage/mroonga/ha_mroonga.cpp:661:8: error: ‘HA_EXTRA_ABORT_ALTER_COPY’ was not declared in this scope; did you mean ‘HA_EXTRA_ABORT_COPY’?
  661 |   case HA_EXTRA_ABORT_ALTER_COPY:
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |        HA_EXTRA_ABORT_COPY
```