packages percona-server-8.0: fix build error (#946)
This is workaround.

I have already reported upstream at
https://perconadev.atlassian.net/browse/PS-10074.
And I have already send to PR at
https://github.com/percona/percona-server/pull/5663.

## Problem

Currently, rpmbuild is failure as follow.

```
wget --no-check-certificate <https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-5.6.51-91.0/binary/redhat/7/x86_64/Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm>
~/rpmbuild/BUILD/percona-server-8.0.42-33/percona-compatlib ~/rpmbuild/BUILD/percona-server-8.0.42-33
--2025-07-01 01:46:52--  <https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-5.6.51-91.0/binary/redhat/7/x86_64/Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm>
Resolving www.percona.com (www.percona.com)... 104.22.9.28, 172.67.8.157, 104.22.8.28, ...
Connecting to www.percona.com (www.percona.com)|104.22.9.28|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: <https://www.percona.com/mysql/software> [following]
--2025-07-01 01:46:52--  <https://www.percona.com/mysql/software>
Reusing existing connection to www.percona.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm'

     0K .......... .......... .......... .......... .......... 43.0M
    50K .......... .......... .......... .......... .......... 36.2M
   100K .......... .......... .......... .......... .......... 61.6M
   150K .......... .......... .......... .......... .......... 2.51M
   200K ..........                                             88.2M=0.02s

2025-07-01 01:46:52 (9.01 MB/s) - 'Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm' saved [215734]

+ rpm2cpio Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm
+ cpio --extract --make-directories --verbose
argument is not an RPM package
cpio: premature end of archive
error: Bad exit status from /var/tmp/rpm-tmp.CWXkdw (%build)
```
Ref:
https://github.com/mroonga/mroonga/actions/runs/15987489896/job/45094672392

Because "Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm" can't
download now.
"Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm" is installed
by the following definition of the spec of "percona-server-8.0.42-33".

```
# Version for compat libs
%if 0%{?rhel} == 7 || 0%{?rhel} == 8
%global compat_prefix         56
%global compatver             5.6.51
%global percona_compatver     91.0
%global compatlib             18
%global compatsrc             https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-%{compatver}-%{percona_compatver}/binary/redhat/7/x86_64/Percona-Server-shared-56-%{compatver}-rel%{percona_compatver}.1.el7.x86_64.rpm
%endif

# Download compat libs
%if 0%{?compatlib}
(
  rm -rf percona-compatlib
  mkdir percona-compatlib
  pushd percona-compatlib
  wget %{compatsrc}
%if 0%{?rhel} > 6
  rpm2cpio Percona-Server-shared-%{compat_prefix}-%{compatver}-rel%{percona_compatver}.1.el7.x86_64.rpm | cpio --extract --make-directories --verbose
%else
  rpm2cpio Percona-Server-shared-%{compat_prefix}-%{compatver}-rel%{percona_compatver}.624.rhel6.x86_64.rpm | cpio --extract --make-directories --verbose
%endif # 0%{?rhel} > 6
  popd
)
%endif # 0%{?compatlib}
```

However, "Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm"
can't download now.

## Solution

Currently, the download URL of
"Percona-Server-shared-56-5.6.51-rel91.0.1.el7.x86_64.rpm" is incorrect.
So, I replace to correct URL in `percona-server-8.0-mroonga.spec.in`.

---------

Co-authored-by: Sutou Kouhei <kou@cozmixng.org>