mysql-server-9.7: follow refactor TIME handring (#1091)
Ref: mysql/mysql-server@6b5b6f5

Use Item::val_time() instead of Item::get_time() since MySQL 9.7.
Item::get_time() is removed in MySQL 9.7.

The following error is resolved by this modification.

```
/mroonga/lib/mrn_condition_converter.cpp: In member function ‘bool mrn::ConditionConverter::get_time_value(const Item_field*, Item*, MYSQL_TIME*)’:
/mroonga/mrn_mysql_compat.h:759:55: error: ‘class Item’ has no member named ‘get_time’
  759 | #  define MRN_ITEM_GET_TIME(item, time, thd) ((item)->get_time((time)))
      |                                                       ^~~~~~~~
/mroonga/lib/mrn_condition_converter.cpp:580:15: note: in expansion of macro ‘MRN_ITEM_GET_TIME’
  580 |       error = MRN_ITEM_GET_TIME(real_value_item, mysql_time, thread_);
      |               ^~~~~~~~~~~~~~~~~
```

---------

Co-authored-by: Abe Tomoaki <abe@enzou.tokyo>