mysql-server-9.7: follow hton_drop_database() argument type change (#1080)
Ref:
https://github.com/mysql/mysql-server/commit/33ebb9b09940a0db391e4e32b43e3c54c5bd922e

The following error is resolved by this modification.

```
/root/rpmbuild/BUILD/mroonga-16.02/ha_mroonga.cpp:2229:25: error: invalid conversion from ‘void (*)(handlerton*, char*)’ to ‘drop_database_t’ {aka ‘void (*)(handlerton*, const char*)’} [-fpermissive]
 2229 |   hton->drop_database = mrn_hton_drop_database;
      |                         ^~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         void (*)(handlerton*, char*)
```

---

MySQL passes `path` in one of the following forms:

- "./${db}/${table}"
- "./${db}/"

This `path` is generated base on `mysql_data_home` by
`build_table_filename()` in MySQL.
`mysql_data_home` is defined as:

  - `char *mysql_data_home = const_cast<char*>(".");`

Therefore, `mysql_data_home` is always ".", and `path` always has one of
the above forms.

Mroonga handles these forms in the `PathMapper` class.
`PathMapper::db_name()` and `PathMapper::db_path()` translate `path`
into Mroonga's db name and db path as follows:

`PathMapper::db_name()`:

- "./${db}/${table}" => "${db}"
- "./${db}/"         => "${db}"

`PathMapper::db_path()`:

- "./${db}/${table}" => "${db}.mrn"
- "./${db}/"         => "${db}.mrn"

Therefore, the expected behavior of `PathMapper::db_name()` is to return
"${db}", and the expected behavior of `PathMapper::db_path()` is to
return "${db}.mrn".

In Mysql 9.7, `schema_name`(e.g."${db}") is passed to
`mrn_hton_drop_database()` instead of `path`(e.g."./${db}/").

If `PathMapper` is given `schema_name` instead of `path`, the behavior
is:

`PathMapper::db_name()`:

- "${db}" => "${db}"

`PathMapper::db_path()`:

- "${db}" => "${db}.mrn"

`mysql_data_home_path` only set in the MariaDB.

Therefore, `PathMapper` behaves correctly whether MySQL passes `path` or
`schema_name`.

For these reasons, this change only updates the argument type and name
of this function.