ha_mroonga: support `HA_EXTRA_ABORT_ALTER_COPY` for MariaDB >= 10.11.12 (#992)
## Issue

We got the following error when we built Mroonga with MariaDB.

```
/home/buildbot/storage/mroonga/ha_mroonga.cpp:471:10: error: enumeration value 'HA_EXTRA_ABORT_ALTER_COPY' not handled in switch [-Werror=switch]
```

## Cause

MariaDB 10.11.12 introduced a new `HA_EXTRA_ABORT_ALTER_COPY` operation
for the ha_extra_function enum to handle aborting ALTER TABLE COPY
operations.

## Solution

This change adds support for this new operation.
ref:
https://github.com/MariaDB/server/commit/f388222d495aa8b445da2653343dfb8233b218a8

---------

Co-authored-by: Sutou Kouhei <kou@cozmixng.org>