mariaddb 11.0: add a new argument into handler::multi_range_read_info_const() (#754)
This PR is the part of support for MariaDB 11.0.4 LTS.

I fail to build of Mroonga with MariaDB 11.0.4 by the following error.

```
/mroonga.dev/ha_mroonga.cpp:14187:48: error: no matching function for call to ‘ha_mroonga::multi_range_read_info_const(uint&, RANGE_SEQ_IF*&, void*&, uint&, uint*&, uint*&, Cost_estimate*&)’
14187 |     rows = handler::multi_range_read_info_const(keyno, seq, seq_init_param,
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
14188 |                                                 n_ranges, bufsz, flags, cost);
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mariadb-11.4.2/sql/log.h:20,
                 from /mariadb-11.4.2/sql/sql_class.h:29,
                 from /mroonga.dev/mrn_mysql.h:57,
                 from /mroonga.dev/ha_mroonga.cpp:25:
/mariadb-11.4.2/sql/handler.h:4260:19: note: candidate: ‘virtual ha_rows handler::multi_range_read_info_const(uint, RANGE_SEQ_IF*, void*, uint, uint*, uint*, ha_rows, Cost_estimate*)’
 4260 |   virtual ha_rows multi_range_read_info_const(uint keyno, RANGE_SEQ_IF *seq,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/mariadb-11.4.2/sql/handler.h:4260:19: note:   candidate expects 8 arguments, 7 provided
/mroonga.dev/ha_mroonga.cpp:14195:51: error: no matching function for call to ‘handler::multi_range_read_info_const(uint&, RANGE_SEQ_IF*&, void*&, uint&, uint*&, uint*&, Cost_estimate*&)’
14195 |   rows = wrap_handler->multi_range_read_info_const(keyno, seq, seq_init_param,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
14196 |                                                    n_ranges, bufsz, flags,
      |                                                    ~~~~~~~~~~~~~~~~~~~~~~~
14197 |                                                    cost);
      |                                                    ~~~~~
/mariadb-11.4.2/sql/handler.h:4260:19: note: candidate: ‘virtual ha_rows handler::multi_range_read_info_const(uint, RANGE_SEQ_IF*, void*, uint, uint*, uint*, ha_rows, Cost_estimate*)’
 4260 |   virtual ha_rows multi_range_read_info_const(uint keyno, RANGE_SEQ_IF *seq,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/mariadb-11.4.2/sql/handler.h:4260:19: note:   candidate expects 8 arguments, 7 provided
/mroonga.dev/ha_mroonga.cpp: In member function ‘ha_rows ha_mroonga::storage_multi_range_read_info_const(uint, RANGE_SEQ_IF*, void*, uint, uint*, uint*, Cost_estimate*)’:
/mroonga.dev/ha_mroonga.cpp:14213:54: error: no matching function for call to ‘ha_mroonga::multi_range_read_info_const(uint&, RANGE_SEQ_IF*&, void*&, uint&, uint*&, uint*&, Cost_estimate*&)’
14213 |   ha_rows rows = handler::multi_range_read_info_const(keyno, seq,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
14214 |                                                       seq_init_param,
      |                                                       ~~~~~~~~~~~~~~~
14215 |                                                       n_ranges, bufsz, flags,
      |                                                       ~~~~~~~~~~~~~~~~~~~~~~~
14216 |                                                       cost);
      |                                                       ~~~~~
/mariadb-11.4.2/sql/handler.h:4260:19: note: candidate: ‘virtual ha_rows handler::multi_range_read_info_const(uint, RANGE_SEQ_IF*, void*, uint, uint*, uint*, ha_rows, Cost_estimate*)’
 4260 |   virtual ha_rows multi_range_read_info_const(uint keyno, RANGE_SEQ_IF *seq,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The cause of this error by the following MaraiDB's modification.

https://github.com/MariaDB/server/commit/009db2288ba8d22c5e8e5e047d8f8694f7097923

I define `MRN_HANDLER_HAVE_MULTI_RANGE_READ_INFO_CONST_LIMIT` to fix
this error and maintain backward compatibility.
However, This modification is difficult to read...