Fix build error on MySQL 5.6.36 and MySQL 5.7.18
The member of Fileld::part_of_key_not_clustered is removed.

  .Tpo -c ha_mroonga.cpp  -fPIC -DPIC -o .libs/ha_mroonga_la-ha_mroonga.o
  ==> centos-6-x86_64: ha_mroonga.cpp: In member function 'void ha_mroonga::wrapper_overwrite_index_bits()':
  ==> centos-6-x86_64: ha_mroonga.cpp:4290: error: 'class Field' has no member named 'part_of_key_not_clustered'
  ==> centos-6-x86_64: ha_mroonga.cpp:4306: error: 'class Field' has no member named 'part_of_key_not_clustered'
  ==> centos-6-x86_64: make[2]: *** [ha_mroonga_la-ha_mroonga.lo] Error 1
  ==> centos-6-x86_64: make[2]: *** Waiting for unfinished jobs....
  ==> centos-6-x86_64: mv -f .deps/ha_mroonga_la-mrn_table.Tpo .