mysql-server-9.7: follow rename Functype value
Ref: https://github.com/mysql/mysql-server/commit/2fe245e177909cb87694f84baf1fa8a486d00c7c

MULT_EQUAL_FUNC is renamed to MULTI_EQ_FUNC in MySQL 9.7.

The following error is resolved by this modification.

```
/mroonga/lib/mrn_count_skip_checker.cpp: In member function ‘bool mrn::CountSkipChecker::is_skippable(Item_func*)’:
/mroonga/lib/mrn_count_skip_checker.cpp:229:21: error: ‘MULT_EQUAL_FUNC’ is not a member of ‘Item_func’
  229 |     case Item_func::MULT_EQUAL_FUNC:
      |                     ^~~~~~~~~~~~~~~
```