mariadb 11.4: follow get_table_name() and get_db_name() API change (#759)
This problem is same as #752.

---

The current version of Mroonga with the MariaDB 11.4.3 fail build as
below.

```
ha_mroonga.cpp: In member function ‘int ha_mroonga::create_share_for_create() const’:
ha_mroonga.cpp:3755:25: error: no match for ‘operator&&’ (operand types are ‘TABLE_LIST*’ and ‘const LEX_CSTRING’ {aka ‘const st_mysql_const_lex_string’})
 3755 |   if (lex->query_tables && lex->query_tables->get_table_name()) {
      |       ~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            |                                                |
      |            TABLE_LIST*                                      const LEX_CSTRING {aka const st_mysql_const_lex_string}
ha_mroonga.cpp:3755:25: note: candidate: ‘operator&&(bool, bool)’ (built-in)
```

Because theses versions modify return value type of `get_table_name()`
and `get_db_name()` in
https://github.com/MariaDB/server/commit/310fd6ff695541247db766baf3ade1e3b4db16e9.

The return type of `get_table_name()` and `get_db_name()` change to
`const LEX_CSTRING` from `const char *` as below.

```diff
-  const char *get_table_name() const { return view != NULL ? view_name.str : table_name.str; }
+  const LEX_CSTRING get_table_name() const
+  {
+    return view != NULL ? view_name : table_name;
+  }
```

```diff
-  const char *get_db_name() const { return view != NULL ? view_db.str : db.str; }
+ const LEX_CSTRING get_db_name() const
+ {
+   return view != NULL ? view_db : db;
+ }
```

I deal with these modifications in this PR.