mysql-server-9.7: follow redactor DATE type
Ref:
- https://github.com/mysql/mysql-server/commit/876fd7ffe0db517a03b2ddc86176b148b44b8d6b
- https://github.com/mysql/mysql-server/commit/fcec2d0fc13916d790da787884a11ef3138a93a0

Use Item::val_date() instead of get_date() since MySQL 9.7.
Item::val_date() is removed in MySQL 9.7.

The following error is resolved by this change.

```
/mroonga/lib/mrn_condition_converter.cpp: In member function ‘bool mrn::ConditionConverter::get_time_value(const Item_field*, Item*, MYSQL_TIME*)’:
/mroonga/mrn_mysql_compat.h:776:14: error: ‘class Item’ has no member named ‘get_date’
  776 |     ((item)->get_date((time), TIME_FUZZY_DATE))
      |              ^~~~~~~~
/mroonga/lib/mrn_condition_converter.cpp:595:15: note: in expansion of macro ‘MRN_ITEM_GET_DATE_FUZZY’
  595 |       error = MRN_ITEM_GET_DATE_FUZZY(real_value_item, mysql_time, thread_);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
/mroonga/mrn_mysql_compat.h:776:31: error: ‘TIME_FUZZY_DATE’ was not declared in this scope; did you mean ‘TIME_NO_ZERO_DATE’?
  776 |     ((item)->get_date((time), TIME_FUZZY_DATE))
      |                               ^~~~~~~~~~~~~~~
/mroonga/lib/mrn_condition_converter.cpp:595:15: note: in expansion of macro ‘MRN_ITEM_GET_DATE_FUZZY’
  595 |       error = MRN_ITEM_GET_DATE_FUZZY(real_value_item, mysql_time, thread_);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
```