mariadb55: don't use std::string
Because MariaDB 5.5.39 says:

    In file included from /home/travis/build/mroonga/mroonga/vendor/mysql/include/my_global.h:79:0,
      from /home/travis/build/mroonga/mroonga/vendor/mysql/sql/sql_class.h:28,
      from mrn_mysql.h:51,
      from mrn_table.cpp:23:

    /usr/include/mysql/my_config.h:654:2: error: #error <my_config.h> MUST be included first!