ci linux: skip Percona Server 8.4 build temporarily
It fails with the following error.

```
...
-- Generating done (2.2s)
-- Build files have been written to: /root/rpmbuild/BUILD/percona-server-8.4.10-10/release
+ pushd release
~/rpmbuild/BUILD/percona-server-8.4.10-10/release ~/rpmbuild/BUILD/percona-server-8.4.10-10
++ readlink mysql-test/var
+ rm -r
rm: missing operand
Try 'rm --help' for more information.
error: Bad exit status from /var/tmp/rpm-tmp.WPWXDQ (%build)
    Macro expanded in comment on line 28: %{_libdir}/mysql/private/ and

    Macro expanded in comment on line 29: %{_libdir}/mysqlrouter/private/. rpm's default build-id link mode rejects
...
```