mariadb 11.0: Use IO_AND_COST type instead of double (#753)
This PR is the part of support for MariaDB 11.0.4 LTS.

I fail to build of Mroonga with MariaDB 11.0.4 by the following error.

```
n file included from mroonga.dev/ha_mroonga.cpp:108:
mroonga.dev/ha_mroonga.hpp:695:10: error: conflicting return type specified for ‘virtual double ha_mroonga::scan_time()’
  695 |   double scan_time() mrn_override;
      |          ^~~~~~~~~
In file included from /mariadb-11.4.2/sql/log.h:20,
                 from /mariadb-11.4.2/sql/sql_class.h:29,
                 from /mroonga.dev/mrn_mysql.h:57,
                 from /mroonga.dev/ha_mroonga.cpp:25:
/mariadb-11.4.2/sql/handler.h:3765:27: note: overridden function is ‘virtual IO_AND_CPU_COST handler::scan_time()’
 3765 |   virtual IO_AND_CPU_COST scan_time()
      |                           ^~~~~~~~~
```

The cause of this error by the following MaraiDB's modification.

https://github.com/MariaDB/server/commit/b66cdbd1eaeed7e96317a03a190c496fd062ec71

I use alias of type name as below to fix this error and maintain
backward compatibility.

```c
#if defined(MRN_MARIADB_P) &&                                   \
    (MYSQL_VERSION_ID >= 110400 && MYSQL_VERSION_ID < 110500)
  using mrn_io_and_cpu_cost = IO_AND_CPU_COST;
#else
  using mrn_io_and_cpu_cost = double;
#endif
```