windows mariadb: add support for 10.5.28, 10.6.21, 10.11.11 and 11.4.5
We need to disable C4090 warning ('operation' : different 'modifier'
qualifiers) because `mysys/mf_keycache.c` has the following warnings:

    D:\a\mroonga\mroonga\mariadb\mysys\mf_keycache.c(3765,1): error C4090: 'initializing': different 'const' qualifiers
      BLOCK_LINK *const *a= _a;
    ^
    D:\a\mroonga\mroonga\mariadb\mysys\mf_keycache.c(3766,1): error C4090: 'initializing': different 'const' qualifiers
      BLOCK_LINK *const *b= _b;
    ^

We also need to use C++17 because WolfSSL's static assert uses C++17
feature but MariaDB uses C++11. So `mysys_ssl\my_crypt.cc` reports the
following warnings:

    D:\a\mroonga\mroonga\mariadb\extra\wolfssl\wolfssl\wolfssl/wolfcrypt/error-crypt.h(321,56): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17'
    wc_static_assert((int)WC_LAST_E <= (int)WC_SPAN2_LAST_E);
                                                           ^
    D:\a\mroonga\mroonga\mariadb\extra\wolfssl\wolfssl\wolfssl/wolfcrypt/error-crypt.h(322,51): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17'
    wc_static_assert((int)MIN_CODE_E <= (int)WC_LAST_E);
                                                      ^
    D:\a\mroonga\mroonga\mariadb\extra\wolfssl\wolfssl\wolfssl/wolfcrypt/error-crypt.h(323,61): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17'
    wc_static_assert((int)MIN_CODE_E <= (int)WC_SPAN2_MIN_CODE_E);
                                                                ^
    D:\a\mroonga\mroonga\mariadb\extra\wolfssl\wolfssl\wolfssl/error-ssl.h(244,55): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17'
    wc_static_assert((int)WC_LAST_E <= (int)WOLFSSL_LAST_E);
                                                          ^