mysql-server-9.7: follow rename of Field_timestampf class (#1082)
Ref:
https://github.com/mysql/mysql-server/commit/9e75348dd1da20328867f7c27d917cf83d9fbe63

The following error is resolved by this modification.

```
/home/horimoto/Work/free-software/mroonga.fork/ha_mroonga.cpp:12431:5: error: ‘Field_timestampf’ was not declared in this scope; did you mean ‘Field_timestamp’?
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |     ^~~~~~~~~~~~~~~~
      |     Field_timestamp
/mroonga.fork/ha_mroonga.cpp:12431:23: error: ‘timestamp_field’ was not declared in this scope
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |                       ^~~~~~~~~~~~~~~
/mroonga.fork/ha_mroonga.cpp:12431:53: error: ‘Field_timestampf’ does not name a type; did you mean ‘Field_timestamp’?
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |                                                     ^~~~~~~~~~~~~~~~
      |                                                     Field_timestamp
/mroonga.fork/ha_mroonga.cpp:12431:69: error: expected ‘>’ before ‘*’ token
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |                                                                     ^
/mroonga.fork/ha_mroonga.cpp:12431:69: error: expected ‘(’ before ‘*’ token
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |                                                                     ^
      |                                                                     (
/mroonga.fork/ha_mroonga.cpp:12431:70: error: expected primary-expression before ‘>’ token
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |                                                                      ^
/mroonga.fork/ha_mroonga.cpp:12431:78: error: expected ‘)’ before ‘;’ token
12431 |     Field_timestampf* timestamp_field = static_cast<Field_timestampf*>(field);
      |                                                                              ^
      |                                                                              )
/mroonga.fork/ha_mroonga.cpp:13715:3: error: ‘Field_timestampf’ was not declared in this scope; did you mean ‘Field_timestamp’?
13715 |   Field_timestampf* timestamp2_field = (Field_timestampf*)field;
      |   ^~~~~~~~~~~~~~~~
      |   Field_timestamp
/mroonga.fork/ha_mroonga.cpp:13715:21: error: ‘timestamp2_field’ was not declared in this scope
13715 |   Field_timestampf* timestamp2_field = (Field_timestampf*)field;
      |                     ^~~~~~~~~~~~~~~~
/mroonga.fork/ha_mroonga.cpp:13715:58: error: expected primary-expression before ‘)’ token
13715 |   Field_timestampf* timestamp2_field = (Field_timestampf*)field;
      |                                                          ^
```

---------

Co-authored-by: Abe Tomoaki <abe@enzou.tokyo>