mariadb 11.4: follow push_warning_printf() API change (#758)
This PR is the part of support for MariaDB 11.4 LTS.

I fail to build of Mroonga with MariaDB 11.4.2 by the following error.

```
/mroonga.dev/lib/mrn_parameters_parser.cpp: In member function ‘const char* mrn::ParametersParser::tokenizer()’:
/mroonga.dev/lib/mrn_parameters_parser.cpp:194:27: error: ‘ER_WARN_DEPRECATED_SYNTAX’ was not declared in this scope
  194 |                           ER_WARN_DEPRECATED_SYNTAX,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
```

The cause of this error by the following MaraiDB's modification.

https://github.com/MariaDB/server/commit/df4bfefbb8f670a986cd9ebe376fe09248dba4a2

`warn_deprecated()` require deprecated version.
However, backward compatibility is important for Mroonga. Therefore we
rarely remove deprecated features.
So, Mroonga output only warning by specifing `999999` into deprecated
version.

---------

Co-authored-by: Sutou Kouhei <kou@clear-code.com>