mariadb 11.4: follow get_foreign_key_list() and get_parent_foreign_key_list() API change (#760)
This PR is the part of support for MariaDB 11.4 LTS.

I fail to build of Mroonga with MariaDB 11.4.3 by the following error.

```
2024-08-27T05:11:48.3976514Z ha_mroonga.hpp:841:7: error: 'int ha_mroonga::get_foreign_key_list(THD*, List<st_foreign_key_info>*)' marked 'override', but does not override
2024-08-27T05:11:48.3977826Z    int get_foreign_key_list(THD *thd,
2024-08-27T05:11:48.3979650Z        ^~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.3981492Z ha_mroonga.hpp:843:7: error: 'int ha_mroonga::get_parent_foreign_key_list(THD*, List<st_foreign_key_info>*)' marked 'override', but does not override
2024-08-27T05:11:48.3982876Z    int get_parent_foreign_key_list(THD *thd,
2024-08-27T05:11:48.3983903Z        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.3988143Z In file included from /root/rpmbuild/BUILD/MariaDB-11.4.3/mariadb-11.4.3/sql/log.h:20,
2024-08-27T05:11:48.3988921Z                  from /root/rpmbuild/BUILD/MariaDB-11.4.3/mariadb-11.4.3/sql/sql_class.h:29,
2024-08-27T05:11:48.3989438Z                  from mrn_mysql.h:57,
2024-08-27T05:11:48.3989778Z                  from ha_mroonga.cpp:25:
2024-08-27T05:11:48.3991013Z /root/rpmbuild/BUILD/MariaDB-11.4.3/mariadb-11.4.3/sql/handler.h:4502:3: error: 'virtual int handler::get_parent_foreign_key_list(const THD*, List<st_foreign_key_info>*)' was hidden [-Werror=overloaded-virtual]
2024-08-27T05:11:48.3992354Z    get_parent_foreign_key_list(const THD *thd, List<FOREIGN_KEY_INFO> *f_key_list)
2024-08-27T05:11:48.3992833Z    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.3993136Z In file included from ha_mroonga.cpp:108:
2024-08-27T05:11:48.3993992Z ha_mroonga.hpp:843:7: error:   by 'int ha_mroonga::get_parent_foreign_key_list(THD*, List<st_foreign_key_info>*)' [-Werror=overloaded-virtual]
2024-08-27T05:11:48.3994723Z    int get_parent_foreign_key_list(THD *thd,
2024-08-27T05:11:48.3995054Z        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.3995613Z In file included from /root/rpmbuild/BUILD/MariaDB-11.4.3/mariadb-11.4.3/sql/log.h:20,
2024-08-27T05:11:48.3996383Z                  from /root/rpmbuild/BUILD/MariaDB-11.4.3/mariadb-11.4.3/sql/sql_class.h:29,
2024-08-27T05:11:48.3996884Z                  from mrn_mysql.h:57,
2024-08-27T05:11:48.3997212Z                  from ha_mroonga.cpp:25:
2024-08-27T05:11:48.3998378Z /root/rpmbuild/BUILD/MariaDB-11.4.3/mariadb-11.4.3/sql/handler.h:4488:3: error: 'virtual int handler::get_foreign_key_list(const THD*, List<st_foreign_key_info>*)' was hidden [-Werror=overloaded-virtual]
2024-08-27T05:11:48.3999489Z    get_foreign_key_list(const THD *thd, List<FOREIGN_KEY_INFO> *f_key_list)
2024-08-27T05:11:48.3999930Z    ^~~~~~~~~~~~~~~~~~~~
2024-08-27T05:11:48.4000374Z In file included from ha_mroonga.cpp:108:
2024-08-27T05:11:48.4001883Z ha_mroonga.hpp:841:7: error:   by 'int ha_mroonga::get_foreign_key_list(THD*, List<st_foreign_key_info>*)' [-Werror=overloaded-virtual]
2024-08-27T05:11:48.4003077Z    int get_foreign_key_list(THD *thd,
2024-08-27T05:11:48.4003597Z        ^~~~~~~~~~~~~~~~~~~~
```

The cause of this error by the following MaraiDB's modification.

https://github.com/MariaDB/server/commit/b3f988d2602d261aedeee63c0f5d8f3aba2ade5c

---------

Co-authored-by: Sutou Kouhei <kou@clear-code.com>